// The prompt behind each motion video, by id (see motion.ts). Only the detail page loads this file.
export const motionPromptText: Record<string, string> = {
 "stephanlivera-df17a2": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "twoclipping-5cba86": "<inputs>",
 "shneural-2abdfa": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "ajith-io-b5626e": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "twoclipping-221cab": "<inputs>",
 "himanshutwtxs-5f4b43": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out",
 "gabrielbuzziv-4ff0c6": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "lexnlin-038035": "using any reference with a fast edit (5s video is enough)",
 "ror-fly-9950f1": "We're going to try a little test. Do you think you could render a recipe motion graphic animation using javascript or html (w/e you think will produce the best) to show the full recipe from start to finish (empty glass to completed cocktail) - Explainer video style - Showing the recipe ingreidents + measurements as they're going into the cup. Should be a 30s video.",
 "notdwd-c2037d": "<inputs>",
 "thismacapital-dfba20": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "ajith-io-c52e09": "Research Distilbook.Make a dynamic 40-second motion graphics video on Distilbook that shows what an incredible motion designer you are. like it's your showreel - Go all out.",
 "twoclipping-6dd14e": "<inputs>",
 "samuel-yostt-891f87": "Run with Opus 5.5 at max effort.",
 "emollick-8661a8": "A video explaining recursion, where every explanation about recursion has a radically different video style, make this self-referential & clever & fast moving.",
 "lexnlin-6161a6": "View repo",
 "steventey-0d20e4": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "alex-prompter-1ea044": "Adopt the role of an expert motion designer. Build a 30-second animated explainer for my business as a single HTML page. 5 scenes. The customer's problem, what I do, how it works in 3 steps, one proof point, and my name at the end. Bold text, smooth transitions, my brand colours. My business [DESCRIBE WHAT YOU SELL, WHO IT'S FOR AND YOUR COLOURS]",
 "majin-appsheet-2d3c1a": "シンまじん式のPV作って",
 "tdinh-me-815acb": "Create an impressive motion design video of a slow-reveal transition that assembles and eventually reveals the TypingMind logo.",
 "thayto-dev-44b911": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "sab8a-364a5a": "Cut a raw talking-head clip into a punchy, fun edit with subtitles, graphics and music",
 "anthonyriera-9b1b2a": "View repo",
 "davidmarcus-a28a60": "make a punchy and modern short video for social that promotes @lightspark capabilities. Needs to be production grade with sound",
 "ultimaxbt-bbebf5": "<inputs>",
 "itsolelehmann-e47532": "4 seasons passing outside a train window, a cozy carriage, a cup of coffee on the table, Grand Budapest Hotel style",
 "linearuncle-5d2bae": "请用Manim给我制作一个导数概念学习的视频，要求通俗易懂，并且有例子，引人思考。配音使用edge-tts",
 "jacksonfall-54b2ac": "make a dynamic 30-second motion graphics video that shows what an incredible motion designer you are,  create all graphics from scratch as if you were a niche branding agency for startup founders, like it's your showreel for a résumé. go all out.",
 "kloss-xyz-fe0c31": "make a video highlighting key moments in the history of AI.",
 "jasonzhou1993-8595e0": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "robj3d3-b18fad": "look at my product roadmap and make a dynamic 15-second motion graphics video that teases the next feature release. go all out and hold nothing back",
 "ho-ba-f3f0e9": "Make a dynamic 30-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.  Make it a video to introduce https://t.co/xdCXEdKZRq Use actual product screenshot/logo/assets Must have music and motion must match the music  Do it like a real professional production video, not like a demo or prototype. Add more animation and motion design; avoid using screenshots as raw; instead, break them down into components/icons so we can animate those too. Make the motions more juicy. Use the best motion design techniques you can.",
 "itisrazak-3ad902": "Research Distilbook.Make a dynamic 40-second motion graphics video on Distilbook that shows what an incredible motion designer you are. like it's your showreel - Go all out.",
 "notdwd-7de38a": "<inputs>",
 "viktoroddy-98c1d8": "Create a launch video for MotionSites AI, just hit 1 million monthly visitors after 8 months after launch.",
 "ismailfahmi-557268": "make a dynamic 15-second motion graphics video that shows what an incredible media intelligent Drone Emprit is, like it's our showreel for a résumé. go all out.",
 "melvynx-6cde6c": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are for <website url>",
 "rossaxbt-3085b7": "<inputs>",
 "tequilafunks-97f6c9": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out",
 "sudo-kiran-49176d": "Go all out.",
 "lukasersil-0ed38e": "Create a bold, dynamic 15-second motion graphics showreel that feels like the ultimate portfolio piece of an exceptionally talented motion designer. Showcase a wide range of advanced techniques: kinetic typography, smooth transitions, 2D and 3D animation, abstract geometry, fluid simulations, particles, distortion, creative masking, compositing, lighting, depth, and seamless camera movement. Keep the pacing fast, confident, and visually surprising, with every shot transitioning naturally into the next. Make it feel meticulously art-directed rather than like a random collection of effects. Push the creativity, polish, timing, and visual impact as far as possible. This should feel like the opening reel that gets a motion designer hired.",
 "nft-chen-5f8bb0": "用 web3D 复刻宫崎骏《红猪》日落海面上的经典空战：白绿红涂装战斗机、紫色积云、海面反光、吉卜力运镜，画面写 just breathe.",
 "axtonliu-0b861d": "每次一个新的模型出来呢，大家都让它去画 “鹈鹕骑自行车” 来判断这个模型的空间能力，基本上都是用 HTML、SVG 来画动画。当我实在看得都有审美疲劳了，我希望你能画一个最复杂、最精细、最精美的 “鹈鹕骑自行车”的动画视频，你可以用任何的技术，不用着急，画一天都可以。",
 "gizakdag-cf4ae6": "Make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it’s your showreel exploring the concept of “Overthinking,” inspired by the attached graphics.",
 "mandelduck-95fd08": "can you make a 3d game where you walk around and spot cats inside of a van gogh painting? we can start with stary night and its town",
 "gorden-sun-041f56": "卡点的3D球体下坠的动画视频：对标专业的Blender做的效果，音乐是多首经典的纯音乐，场景按音乐切换，3D球体下坠时在3D场景的物件中弹跳，按音乐的节奏点亮物件。带一些幽默的元素。",
 "ajith-io-4c248f": "Make a dynamic 40-second motion graphics video on Distilbook that shows what an incredible motion designer you are, like it's your showreel - go all out. Use the Oppenheimer theme music as inspiration, but compose it yourself.",
 "polydao-7a572b": "Make a dynamic [24]-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a resume. Go all out.",
 "ajith-io-ea7f2d": "Take reference from the given video (download it) and use the same visual style.",
 "ayushunleashed-ece3e3": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out",
 "chatgptastra-0d95c7": "以动态设计师的高级审美，制作一段动态的15秒动态图形视频",
 "ultimaxbt-2ddf1e": "<inputs>",
 "monokern-ade5b6": "make a dynamic 20-second motion graphics video that shows what an incredible motion designer you are, psychedelic and hypnotic. make it feel like a showreel piece. go all out.",
 "kloss-xyz-15182a": "Use Python to generate a 9:16 chaotic brain rot video with excellent motion + sound design and render it using ffmpeg. Put your own personal spin on it so it’s aligned with Anthropic’s new launch. Also fully express what it’s like to be a very creative LLM used by me every day from your POV to give it some extra personality.",
 "0xnfrith-5be616": "make me an animation to explain why celld earns its place.",
 "math-files-39c9d0": "make a dynamic 20-second motion graphics video related to mathematics that shows what an incredible motion designer with mathematics skills you are, like it's your showreel for a résumé. go all out",
 "hanifproduktif-54bdee": "You are applying as a motion designer in my agency. Make 15s video to showcase your skills and capabilities. Send me a showreel",
 "nikolajankovic-ce4ff4": "make a hand-drawn stop-motion animation;",
 "ddryo-loos-300829": "Lism CSS ver.1.0 をリリースする時にSNSに動画を投稿したい。あなたがどれほど素晴らしいモーションデザイナーかを示す、シンプルかつダイナミックさもある15秒のモーショングラフィックスビデオを作成してください。",
 "eyishazyer-af035b": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "blue-clarity-ef56d0": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "roundtablespace-d3a1be": "make a 15-second motion graphics showreel that proves what an incredible motion designer you are, go all out.",
 "1littlecoder-9fef89": "make a dynamic 10-second motion graphics video that shows who are you as Opus 5.5 - be as creative and dynamic as possible. Avoid the frames and texts on the corners which are typical ai made giveaways!",
 "sayan-shanky-f850d8": "show me what goes on inside an AI data centre.",
 "yunn260414-60d996": "帮我用js制作一个视频，主题是：什么是Git",
 "brainextends-e19ac3": "Create a complete, polished Spotify-themed motion graphics video from the following brief. This prompt is self-contained: no reference video or supplied assets are required.",
 "pankajkumar-dev-0bee87": "create a motion design video of a poster breaking out of its own frame.",
 "sudo-kiran-b055de": "make a dynamic 30-seconds motion graphic video about the distilbook like a product explainer the video has to be very incredible (product url)",
 "raphaelaubryy-4b137e": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "jake11moran-a269c4": "View repo",
 "arjunsh1607-93005d": "create a 15 sec motion graphics showreel for @pixeluplabs, be extremely detail oriented and go all out",
 "codestackr-c071bf": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a resume. go all out",
 "hqmank-7c61f1": "Make a dynamic 20-second motion graphics launch video for my open-source project jev-browser-skill ('Give a site. Write a goal. Jev clicks.'), like it's the hero video on its GitHub README. Go all out.",
 "ratheejaisal-1f4538": "build me a beautiful launch video 20 seconds or under that shows all our key features, make it fast paced and fit our brand",
 "tankazunori0914-0fc886": "今日何曜日だっけ？BGM付きの30秒のかっこいいモーショングラフィックスで教えて（全力を出してください）",
 "prasad-pilla-2c0cba": "make a dynamic 15 second motion graphics video that shows what an incredible motion designer you are, for @tryAlanAI. go all out.",
 "dale-vaz-cc612a": "create a self contained aesthetically pleasing, breathtaking animation of the Sahi Trading Terminal. it should start with a single dot on a black screen and then have multiple windows show up on the screen such as Charts, Positons , Option Chain, Watchlist. And zoom into and out at multiple scales. Finally the camera zooms out to make the desktop look like a point in space. And then it zooms back in to reveal a mobile screen in landscape mode with a chart in one half and an option chain in another. The video ends in Sjngle Screen Trading on SAHI",
 "sarut0bisasuke-cefa43": "Render a recipe motion graphic animation using JavaScript or HTML (whatever you think will produce the best result) to show the full recipe for a White Russian from start to finish, empty glass to completed cocktail. Explainer video style, showing the ingredients and measurements as they go into the glass. It should be a 30s video.",
 "maxalexweber-67688b": "Make a ODATANO edit that goes hard",
 "ezshine-c90d73": "设计个动画，介绍本项目的各项特性，像是专业的产品介绍宣传片，最后要生成 16:9 的mp4 视频",
 "samuel-spitz-974923": "Create a motion graphics video that feels like the centerpiece of a world-class designer’s showreel. Treat it as your résumé: showcase your full range, push the craft as far as possible. Go all out.",
 "tak3sh8-be5012": "Prompt 1: \"Do a quick hand-drawn whiteboard animations explaining what is replica symmetry breaking in the SK model\"",
 "hbcoop-de365c": "Create me a motion video of your choice, with the sole purpose of flexing Opus 5.5 capabilities.",
 "aistocksavvy-3fb9f5": "Create a bold, dynamic 15-second motion graphics video that showcases your best motion design skills as if it’s the highlight of your portfolio for a dream job. Bring sharp timing, smooth transitions, and standout visuals. Push your creativity and make every second count.",
 "techyoutbe-945b56": "I want you to create a highly professional SaaS product launch video. Go and find some SaaS, preferably just one that people know, so it's easier to identify with it. Pick that, and then make sure to get actual assets and images and all of that stuff from the internet. Turn it into these typical, very professionally edited, motion-graphics-styled product launch videos that you see people making on Twitter when they launch new SaaS products (which are showing off the features, the benefits, and all of these things)",
 "micheleharmonic-77628e": "Make a GravityDEX x Gojo Satoru edit that goes hard",
 "lemomo-ai-0d9cff": "Create a tutorial video explaining how to create videos using Lemo-Opuscar skill (Opus 5.5) , in a [Whiteboard Explainer] style.  One prompt, one answer, then ship film.",
 "triglyceee-bd5b08": "réalise une vidéo résumant la vie politique au Maroc depuis l’indépendance",
 "zheke-38deff": "Hello Opus 5.5 show me what an incredible motion designer you are.",
 "deifosv-04e4d3": "Create a high energy launch video, showing live stats from the website, show that users can play on desktop and mobile and multiple themes, if need, give me a prompt to generate the song using Suno",
 "sudeepsd-1a3485": "make a dynamic 15-second motion graphics video of what you know about @tryflexprice that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "visheshbaghell-3aba37": "build me a product demo for my site using /brag skill. make sure to emphasize on all features",
 "imthatcarlos-e04bfe": "make a modern slick and punchy video for sherwood protocol. feel free to take branding or components from the landing page or app. the goal is to highlight how it enables agentic hedge funds, explaining it simply",
 "paulo-kombucha-96431c": "make a dynamic 15-second motion graphics video to talk about our referral program",
 "gigabit-million-16b3a0": "9月25日～9月26日にSteamにリリースされたゲームの紹介ニュースを、ゲーマーの目線で各ゲームの面白そうなポイントをわかるように、見やすい約60秒ぐらいのモーショングラフィックスで作ってください",
 "sudo-kiran-6609ed": "create best motion graphics explainer of the (your product) with very good script and good design colors and good music make sure the video should be incredible and people should feels like watch it many times.. it has to be in 30 seconds good and very intresting, it has to be best of the best of the best of the best video",
 "demonugc-4c5753": "<inputs>",
 "jhylee95-e1152f": "You're a world-class motion designer building a Supademo launch video. Research and land our core value and narrative. Scenes should be dynamic and confident: hook in the first second, then distinct beats for product proof and AI. Brand-accurate UI, type, color, and motion. Score the music so every cut, animation hit, and scene change lands on a beat or drop; retimed until synced. Social energy, quick cuts",
 "sachaarbonel-8f14f4": "Create a professional product launch video with motion graphics. You have access to the designs in pen",
 "gdgtify-287ddf": "Create a 20.00-second kinetic spoken-word film titled “BUILD THE FLOOR.”  Treat this as an original miniature speech staged entirely through typography. Every line changes the architecture of the frame. The final declaration must stand on something the earlier words physically constructed.  Deliver one self-contained HTML file, 1080×1080, targeting 60fps, using SVG and/or Canvas. Embed all required assets.  ART DIRECTION Background #102820. Paper # F4E9D5. Structural accent # F2B544. A literary editorial world with the scale and confidence of a public monument. Use a high-contrast serif for the speech, a heavy grotesque for load-bearing words, and a restrained monospace for small timing marks. No distressed protest-poster clichés, megaphones, flags, crowds, microphones, or stock footage.  ORIGINAL SPEECH — EXACT WORDS, EXACT ORDER “We were told to wait.” “So we learned the weight of waiting.” “Then one voice made room.” “Then another.” “Now the floor belongs to us.”  Do not attribute these words to any real person. No extra slogans. The complete speech must be understandable without audio.  CENTRAL VISUAL RULE Words have assigned architectural roles. WAIT is a lintel. WAITING is a suspended load. VOICE is a support. ROOM is an opening. FLOOR is a platform. These roles must emerge from the actual letterforms, not from separate illustrations placed behind text.  STORYBOARD 0.00–3.00 “We were told to wait.” The sentence occupies a narrow horizontal opening beneath a massive WAIT. The opening slowly compresses while the sentence remains readable. The pressure comes from the layout, not camera shake.  3.00–6.50 “So we learned the weight of waiting.” Reveal the sentence in spoken phrase groups. WAITING lowers on two fine vertical rules. Those rules become suspension cables. A baseline bends under the visual load using a controlled vector deformation.  6.50–10.00 “Then one voice made room.” VOICE enters vertically and rotates into a structural support. It lifts one end of the baseline. The counter of the O in ROOM becomes an aperture. The next composition is revealed through that aperture.  10.00–12.50 “Then another.” A second support arrives. The tilted structure levels. This is the first moment of perfect horizontal alignment in the film. Use a brief stillness to make the change feel earned.  12.50–16.00 “Now the floor belongs to us.” Earlier structural words assemble into a platform. The final sentence settles onto it. US receives emphasis through shared alignment and scale, never through a separate flashy effect.  16.00–18.00 Hold the complete declaration. A slight release of tension travels through the supporting rules. No new text. No restless decorative motion.  18.00–20.00 The camera tracks beneath the completed platform. Its underside fills the frame and becomes the opening WAIT lintel. Under full occlusion, return hidden elements to their initial positions. Reveal the exact opening composition.  CHOREOGRAPHY Do not force the speech onto a dance beat. Use a cue sheet based on phrases, pauses, and emphasis. Phrase reveals should follow reading order. Allow at least one 400ms moment of absolute stillness. Use critically damped motion for settling loads. Use controlled elastic deformation for the baseline only. Make the changes in available space carry the emotional progression.  TYPE IMPLEMENTATION Use actual glyph paths for structural words. Preserve counters and legibility during deformation. For transitions between unrelated words, use occlusion or matched structural edges; do not interpolate arbitrary path points. Keep the currently spoken phrase readable before it becomes architecture.  ENGINEERING Implement window. seek(t) as a deterministic scene renderer. No accumulated physics, autonomous CSS transitions, or changing random values. Use time-remapping curves and analytic transforms. Use a 20-second periodic timeline with render(0)=render(20). Provide fixed-step access at n/60 for 1200 export frames. Audio is optional and off by default; no browser speech synthesis or autoplay dependency.  QUALITY GATE Inspect eight representative frames. Check that the speech reads in the correct order. Check that structural transformations never destroy a line before the audience can read it. Check the final platform is visibly assembled from earlier elements. Return the complete HTML implementation.",
 "ercankeskinx-ec2568": "Build 5 completely different scroll-based sections, decide the context & layout yourself.",
 "influencer-seo-ce8c33": "make a dynamic 15-second motion graphics video for @fal that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out. Use the fal API.",
 "agonaliu-466a8f": "Make a dynamic 15-second motion graphics video for Trezio app that shows what an incredible motion designer you are, like it's your showreel for a résumé. Get it!",
 "daniel-haida-8691d4": "You are the senior motion designer, product designer and Remotion engineer for Taxtello.",
 "bthreeagency-b9b8d9": "Using the linked Figma frame build a badge unlock screen. Match the design exactly. Use the file's assets, lighting, type and layout and add only the motion. Animate the badge so it feels premium and celebratory. Build its scene and then celebrate with gold particles. Treat the badge as a solid 3D object that tilts toward the",
 "henkvaness-0e06af": "make educational video out of article.",
 "ndhabarde11-f155b4": "make a dynamic 15-second motion graphics video in portrait mode that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "topi-003-9ca6b5": "あなたがどれほど素晴らしいモーションデザイナーかを示す、ダイナミックな15秒のモーショングラフィックスビデオを作成してください。履歴書用のショーリールのような感じで、全力でやって。",
 "rendesr-86be44": "Make a dynamic 15 second motion graphics video that shows off what an incredible motion designer you are. Imagine it's your showreel for a resume!",
 "bogdandragomir-35e024": "Create an intro for https://t.co/wQXZTaqf1b highlighting what it does.",
 "en-ra-81c6dd": "make a dynamic 15-second motion graphics video for RedSeed AI (Replace with your Project) that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "jesscaroline7-1ff7cb": "make a dynamic motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out",
 "theviableedge-9065be": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, and can be the hero asset for the course landing page.",
 "0xfemyn-e114d3": "make a dynamic 15-second motion graphics video for AIsa. Go all out.",
 "misbahsy-80eaec": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "reyzostyle-b55864": "make a dynamic 10 second motion graphics video about https://t.co/Zi6zrTvzqI that shows what an incredible motion designer you are, like its your showreel for a resume. go all out",
 "mdaman010-e7226a": "Show me what goes on inside an AI data centre.",
 "motiondsgnr-9dcfa6": "Make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a resume. Go all out.",
 "astrodevil-3f2054": "make a dynamic 15-second motion graphics video that shows what an incredible work Studio1 is doing, you will get relevant info from case study, create like it's a good showreel for a Studio1 intro launch. go all out.",
 "hoyoyoda-3a5c08": "한국의 추석에 어울리는 요소를 서치해서 픽셀 애니메이션을 구성해서 제작해줘",
 "macrohou-33959d": "[gave access to Ren repo] Make a dynamic 30-second motion graphics video for Ren that shows off your motion and sound design. Go crazy.",
 "madhav-xo-f97f20": "make a 10 sec video on whatever you know about me",
 "buildfastwithai-ed9447": "Build a Douglas A-1H Skyraider in Three.js",
 "rames-jusso-589f80": "140 BPM rusko/skream style UK dubstep",
 "topi-003-b0e12c": "この画像の女の子がエキサイトなダンスをする、ダイナミックな15秒のモーショングラフィックスビデオを作成してください。履歴書用のショーリールのような感じで、全力でやって。",
 "ik-builds-b8bdcf": "Create a 15s motion-graphics film explaining {{PRODUCT}}. HyperFrames + GSAP, no voiceover, no footage.",
 "wani-shola-16ca7a": "Make a showreel-style motion graphics video for my portfolio website, https://t.co/xZFGCqi73s, using Remotion. It should show what I do as a developer relations engineer, like a showreel for my résumé.",
 "manuelogomigo-f33ca9": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a flowdrive. go all out.",
 "mrtanviir-132457": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "0xevinho-3777d8": "make a similar version but with a crypto reference",
 "chrisjdimarco-f068db": "make a samurai dude in only javascript and have him doing a routine in a single spot going through various seriously impressive poses and motions and positions in a fiery awesome display",
 "jayscambler-3f8889": "make a dynamic 20-second motion graphics video for fundmycompute that gives an overview of the platform and shows what an incredible motion designer you are",
 "utopyaszx-1b2f94": "make a dynamic 15-second motion graphics video for Bold Pilot that shows what an incredible motion designer you are, like it's your showreel for a resume. go all out.",
 "aschapmann-131210": "Act as a senior motion designer and build a 30-second launch video for [product] in Remotion, entirely in code so I can edit and re-render it: first read my landing page and codebase to pull the real story, copy, colors, font and logo file (trace the logo to SVG so it stays sharp and can be animated), then write the video as one story (why the market matters, why it's painful today, how [product] fixes it, what you get) in 4 to 5 scenes with one short title each, animate everything like a premium product film (kinetic typography word by word, spring easing, smooth camera pushes and pans, depth and glow, elements that build in on the beat instead of just appearing), keep each scene on screen long enough to read, add one soft sound effect for every element that appears and silence otherwise, and end on a memorable animated logo reveal with the tagline and URL, then render it, check the frames yourself and fix anything that overlaps, clips or feels rushed before showing me the result.",
 "marklaunches-3b9492": "build me an incredible video for my app. make it emotional.",
 "web3wesley-7bb108": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "reflex-cloud-72ffe5": "You're a world-class motion designer, and this is your 15-second résumé reel. Make it dynamic and confident: open with a striking hook in the first second, build through a sequence of distinct techniques (typography, shape play, camera moves, colour shifts), and land on a clean, memorable final frame. Pacing should feel like it's cut to music. Go crazy.",
 "1stnoel-c20a89": "Make a 1-minute educational video about https://readsotto.app/ with synthesized voice narration.",
 "ryzoft-4f85bd": "I want you to imagine a story. And then using threejs I want you to create full animation, star wars 80s-level quality 90s cartoon out of the story you imagine.",
 "kamstudiolabs-c9bb28": "Make a 90-second animated short film about a bug that doesn't want to be fixed.",
 "devius-maximus-beab45": "make a dynamic motion graphics video for our project dubz up, show what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "elliot-garreffa-f334bc": "Give it your product URL and brand guidelines plus one or two reference videos, list any specific features you want in a storyboard first, and use Remotion to build it.",
 "adamdesgns-478d6d": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out. (About the pipefitters bible)",
 "andginja-333d32": "make a 15-second showreel about my website. Go all out.",
 "l3d1c-0e35a3": "create a motion design prompt for an ad for our site",
 "wozu-co-242285": "please create me a motion design / launch video for supasito dot com it should be under 15 seconds.",
 "buildfastwithai-53234e": "generate a creative mp4 video on indian civilisation with music and sound effects.",
 "allforbigfire-86ff3c": "もしかしてロボットアニメみたいな3機の乗り物が変形合体してロボットになるシーンもアニメ風3D CGで作れますか。",
 "tstfully-0aa6b4": "make a 15-second motion graphics product ad: paste a YouTube video, get every word.",
 "bizibeast-10f264": "Research Bento.surf. Make a dynamic 40-second motion graphics video on Bento.surf that shows what an incredible motion designer you are. like it's your showreel - Go all out.",
 "heyiammallik-e72d17": "you are a pro motion designer. analyze my portfolio and make a ~30 second video from it. check what are the recent trending techniques used for motion and sound design. question your strategy and plan, if it doesn't feel like done by a pro designer, start over. every frame matters from the first frame to the final frame. go crazy",
 "sudiyasa-f48ac9": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out  do this to thank the first 100 users of @eyezonbot",
 "davidshulmanfl-371638": "Create a 60 second music video in the style of Peter Gabriel's Sledgehammer and Big Time. But use modern references and figures. Also create the song, something sounds like it would fit on Peter Gabriel's So album.",
 "demitiyageekzen-7770ad": "用你最强的思维和能力，根据对我的了解，自行寻找我可能喜欢的主题，制作一个30s的视频还有互动html，尽可能的展示你的前端能力！",
 "faroukzy-9ff23e": "make a 4-minute animated short that blows my mind.",
 "m1n9-k7-ff9ab9": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out",
 "quickdesignio-dd93d0": "make a dynamic 15-second motion graphics video that shows what an incredible quickdesign is! and also  shows what an incredible motion designer you are!",
 "rebutonepress-810f78": "听说 opus 5.5 做视频很强，请让我见识下。结合本机环境风格，做一个关于时间的故事，5分钟。要完整的视频，音频和字幕。需要什么工具自己在devshell配置，渲染完成后只留视频成品文件，其他全部清理干净。",
 "slvdev-64c45a": "create 15+ sec self-promotion promo",
 "sudo-kiran-4f8b59": "make a dynamic 30-seconds motion graphic video about the distilbook like a product explainer the video has to be very incredible",
 "xelandre-363f00": "Code-driven animation: an HTML/JS page where every frame is calculated from the time, captured frame by frame with headless Chrome (Playwright), then assembled with ffmpeg into an MP4 with motion blur and code-generated sound.",
 "justincooperman-e7bbc4": "Make an animated clip about Tented's image gen capabilities where users ask for branded images and see them added to content",
 "henkpoley-3d3407": "Make a painful to see 1 minute motion graphics HTML page that shows what an absolutely terrible motion designer you are, like it’s a showreel designed to get your résumé immediately rejected. Do the absolute bare minimum.",
 "fractadev-149adc": "Analyze my frontend project, use the actual components from the product, and create a dynamic motion graphics video that showcases and sells my SaaS. Make it feel like a high-end product launch. Go all out.",
 "gautam-mer1-2ae354": "an Apple-style 30s video of my app",
 "levabashidze-2d713a": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out. dont ask just make",
 "miskinho-443898": "make  1 dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for Quetzal. go all out.",
 "zaqailo-212ad3": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "crazyalphaaa-bc7e75": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "fionntobin-97b7af": "Make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "francoxavier33-d2dfd2": "make a hype demo/launch video for @momwiseai",
 "itsuki-dev-10942d": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "kangaroohere-b10f8d": "make a dynamic 20-second motion graphics video for my newsletter that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "kyonax-on-tech-aabc1d": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "loicrambo-ad6830": "make a dynamic 20-second motion graphics and animation video that shows what an incredible motion designer and animator you are, like it's your showreel for a résumé. make it about the cycle of life showing the same individual going from childhood to adolescence to the 9-5 cycle, to family life to elder life and death, then cutting ready to loop to the beginning.  go all out , use whatever you need.",
 "madebyjmayala-b9204d": "make a dynamic 15-second motion graphics video promo about gene spectra, use assets from the current live site where relevant. go all out.",
 "tolgayhickiran-e90799": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "antonio-kodheli-490109": "<inputs>",
 "oliahmed205-3e31c4": "Make me a 15 sec promtional video for my product using product screenshots and assests, Be a Highly preofessional Video Editor.",
 "aisongman-71ffac": "Create a 1-on-1 card game like Hearthstone.",
 "danilowm-d3720d": "Install the HyperFrames skill from the terminal first, then run this in Cursor.",
 "kmasiff-cc72cb": "make a dynamic 20-second motion graphics video that shows what an incredible our email verify tool is, put all the use case you can imagine. go all out'",
 "pluginplay-3d4006": "pixel art boomerang render of the history of LLMs. then RSI. then it goes fucking crazy. 15 seconds max. self contained .html",
 "rammanq-f5a90f": "Make a dynamic motion graphics video that shows what an incredible platform AllInvestView is. Go all out.",
 "robvjourney-ce3e1a": "Can you make a 15-second motion graphic video of https://t.co/4AZZ7AlJvi? Go ALL OUT and make the most badass video you possibly can use everything you've got.",
 "vanshwtfff-db0466": "make a dynamic 10 second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a resume.",
 "3xtihor-0f6911": "Make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. Go all out.",
 "amol909s-27533e": "make a dynamic 20s motion graphics video that shows what an incredible motion designer you are, like it's your showreel for this app commotion, highlighting tiling layout, auto model classifer and other features you deem fit to be in video. Go all out.",
 "cansincengiz-me-cf68dd": "merak ediyorum ne kadar iyi bir hareketli grafik tasarımcısısın. Bunu bana kanıtlamak için 15 saniye sürecek bir hareketli grafik videosu istiyorum senden. Bu video https://t.co/TdKZEIYaxO 'i tanıtacak ve x üzerinde 10.000 kişinin karşısına çıkacak. Elinden geleni yap",
 "ghinaiya-nirmal-5d8fec": "make your own 15-second motion reel. go all out",
 "johnsavage-ai-b091c0": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a resume. go all out. use only code",
 "leonkohli-6dc01b": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "marouanegazouzi-6071d5": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "mehul4795-4a7007": "Create a product launch video for ocrX Android app.",
 "safarkhanshuvo-ffd52d": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out",
 "sahildesigner23-ee3155": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "abderrahmen-g-9e8ed0": "You are a professional videographer. Create me a high-definition, creative, playful, and joyful video that you enjoy watching, that has sounds matching the frames using JavaScript. Use as much as possible of the input images—hand-drawn—to make it more creative and more authentic from input-pictures. You can also be inspired by, but not copy, the videos created by you in video-examples/, especially this: video-examples/twitter_claude.mp4. You're really creative, so produce the best of what you can.",
 "palashbagchi11-0a4b6b": "Add a good fast royalty free music to this video, and make 2 versions - 1 landscape, and another portrait",
 "x4b47x-9cc84f": "Create a pure javascript animation. 30-60s, vertical 9:16, paper cut-out shadow theatre style with gentle, fitting audio (made in code) on the topic: What makes a place feel like home?",
 "kamstudiolabs-447565": "Build a 45-second machine that plays an original piece of music, where every note comes from a visible collision.",
 "grace-sunnyy-29bc61": "制作一段 15 秒的动态图形视频，展示你是一位多么出色的动态设计师，就像是你简历上的作品集一样，使用任何你认为能产出最佳效果的工具或技术。你拥有完全的创作自由，优先追求卓越的视觉设计、大胆的艺术指导、引人注目的构图和富有力量的动态表现，让每一秒都有价值。全力以赴。",
 "blueoctopusai-dd17bd": "Make a motion graphics video that explains how the First & 10 Yellow Line works.",
 "apoorvjain25-d24184": "make a 20-second video about anything, your call; make it crazy.",
 "deebeeeff-50fcd0": "Attach the brand image along with the prompt.",
 "listudio-820c7b": "Investigate my project GenVizu: https://t.co/5RaGMqn7rF Create a video for product release. Used for Hero and GTM materials on websites.",
 "thilina-a-891c09": "make a dynamic 25-second motion graphics video that shows what an incredible motion designer you are. Highlight the recent changes [1.3, 1.4] we made with the last few updates.",
 "amitsingha89-150378": "Make a professional explainer video for https://anuprerna.com for a first-time visitor.",
 "blushpetal795-0c85c2": "Make a dynamic 15-second motion graphics video of me introducing myself to a recruiter. Use all the motion design skills you have, like it's your showreel for a resume. Go all out.",
 "ceowinkz-7c776b": "make a dynamic 15 second motion graphics video pitching my Amazon wholesale company, Winkz Enterprises, to a brand. show why they should let us sell their products. go all out.",
 "ibrahimwasim240-809370": "make a dynamic 25 second motion graphics video that shows My skills like a showreel for a resume. go all out",
 "jazzen-chen-4542ae": "make a dynamic motion graphics video about my project AgentHud.",
 "lester-tyy-f897f7": "Study how this https://t.co/SR0AyULLNp works and use Remotion to make a product showcase video.",
 "majorbaguette-fb11d7": "make a presentation video for Brieform, 30 seconds long",
 "nolkeeg-bf062e": "Please do not reference any previous memories or skills. I've been seeing all of these motion graphics examples on X of people making cool videos with opus 5.5. So - I want you to just show off for me. You pick the design style, the look, subject etc. I just want to be extremely impressed by the motion graphic video that you create. I want you to destroy GPT 6 when it comes to motion graphics video - because astra just wants to give me a stupid glorified powerpoint presentation.",
 "souravbhar871-61f424": "make a dynamic 10-second motion graphics video that shows who are you as Opus 5.5 - be as creative and dynamic as possible. Avoid the frames and texts on the corners which are typical ai made giveaways!",
 "spearwtf-3c1fd1": "Create a 30sec pitch video for @chaindotwtf",
 "teslachartz-c58b32": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out",
 "ai-baymax-0ef9dd": "make a 1-min promo for this product from the codebase.",
 "anas0ra-e57aea": "fait moi une vidéo sympa pour https://heeya.fr",
 "iammxfschr-d68f90": "nice. wir brauchen ein launch video für den release. kannst du das machen? so a la anthropic like? hab da was gelesen und der prompt war \"\"make a modern slick and punchy video for a modern startup that works on inference\"",
 "kikelopezdesign-7cc9e8": "Make a 20 second video about my portfolio from scratch, using only the portfolio's own resources",
 "leadnotifi-e83f94": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "rneayan-474bcf": "make about my studio with Risograph style",
 "rneayan-ea6129": "Make Motiongraphic about my studio with Oscilloscope style",
 "samaote-5e2fc2": "make a dynamic lyrics motion graphics video based on the attached music, perfectly syncing the lyrics and animation to the vocals and beat. make it feel like an incredible motion designer’s showreel for a résumé. go all out.",
 "shinskinakamoto-20190b": "Make a dynamic 15 second motion graphics video that shows what an incredible motion designer you are, like its your showreel for a resume, go all out!",
 "umangratani-57f86a": "make a dynamic 15-second motion graphics video that shows what an incredible motion designer you are, like it's your showreel for a résumé. go all out.",
 "anilraok-eff262": "I want you to imagine a story, that subtly promotes grid genius. Or it can not even have grid genius, but something that aligns with our app and helps us get more eyeballs when posted on social media. Then using threejs/javascript I want you to create full animation, Pixar-level quality out of the story you imagine",
 "kantamk-61f410": "make a video that could go viral.",
 "parkerrex-1a54fe": "explain a token bucket rate limiter, canvas only, no libraries, every frame a pure function of time so my renderer can screenshot it.",
 "charlesmendez-73b6e4": "I Want you to make a modern slick and punchy video for https://t.co/a3zrq7DV3N with an example of a user creating a chatgpt ads campaign, then connecting their metrics, understanding attribution, then connecting a voice agent to it, the agent responding, then doing follow up, adding humans in the loop and then providing analytics.",
 "gonzalomacagno-2de1a9": "Necesito que armes un reel con esta info en 10 segundos, bien publicitario",
 "kamstudiolabs-0b0824": "Make a 45-second silent short film with no dialogue, where sound tells half the story. Invent the story."
};
