// Skills: ready-made creative recipes the assistant follows when you run one (a shoot, a campaign, a short video).
// `playbook` is what the assistant is given when a skill is used. Wording is Eclipse's own; previews are Eclipse's sample content.
export type Skill = { id: string; name: string; blurb: string; minutes: number; image: string; kind: "photo" | "video"; playbook: string };

export const skills: Skill[] = [
  { id: "product", name: "Product photoshoot", blurb: "Turn one product photo into a set of polished campaign shots.", minutes: 4, image: "/carousel/card-5.jpg", kind: "photo", playbook: "Goal: a set of polished campaign shots of one product. 1) Ask for the product (name, a reference image from the Library if there is one) and the mood only if they are missing. 2) Write four distinct prompts: hero on seamless backdrop, in-context lifestyle, close-up detail, flat-lay. Keep the product described identically in all four. 3) Render each with generate_image (1:1 for the hero, 4:5 for the rest), then tell the user which render is which. 4) Offer to send the winners to a connected app." },
  { id: "interior", name: "Interior styling", blurb: "Restyle a room in several looks while keeping the layout.", minutes: 5, image: "/carousel/card-8.jpg", kind: "photo", playbook: "Goal: the same room restyled in several looks. 1) Get the room type and the layout facts that must not change (windows, doors, proportions). 2) Propose three looks (for example Japandi, warm industrial, coastal) and write one prompt each that restates the fixed layout. 3) Render each with generate_image at 16:9. 4) Summarise what differs between the looks." },
  { id: "short", name: "Short product video", blurb: "A vertical clip for socials, from a single prompt and a photo.", minutes: 8, image: "/carousel/card-4-poster.jpg", kind: "video", playbook: "Goal: a short vertical product clip plan. Video rendering is not available yet, so: 1) Ask what the product and the one feeling are. 2) Write a 3-shot plan (hook, product moment, payoff) with a still-frame prompt per shot. 3) Render the three stills with generate_image at 9:16 so the user can review the look. 4) Say plainly that stills are what can be produced today." },
  { id: "fashion", name: "Fashion lookbook", blurb: "Editorial looks with a consistent model and wardrobe.", minutes: 6, image: "/carousel/card-2-poster.jpg", kind: "photo", playbook: "Goal: an editorial lookbook with a consistent model and wardrobe. 1) Fix a one-paragraph character description and reuse it word for word. 2) Plan four looks with different garments and locations. 3) Render each with generate_image at 4:5, repeating the character paragraph. 4) Save the character description with remember (topic characters)." },
  { id: "portrait", name: "Portrait shoot", blurb: "Studio-quality portraits of one person across several styles.", minutes: 4, image: "/carousel/card-9-poster.jpg", kind: "photo", playbook: "Goal: studio portraits of one person in several styles. 1) Confirm what the user wants captured (mood, wardrobe), no identity claims. 2) Write four prompts: classic studio, natural window light, cinematic night, editorial colour. 3) Render with generate_image at 4:5. 4) Ask which style to push further." },
  { id: "campaign", name: "Brand campaign", blurb: "A full set of matching visuals and clips for a launch.", minutes: 12, image: "/carousel/card-6-poster.jpg", kind: "video", playbook: "Goal: a matching set of launch visuals. 1) Pull the brand's style and products with recall. 2) Define one visual system (palette, lighting, lens feel) in two sentences and keep it in every prompt. 3) Plan: one hero (16:9), two social squares (1:1), one story frame (9:16). 4) Render all four with generate_image, then summarise the set and offer to send it to a connected app." },
];
